### ISSUE TITLE
Combine two actions in bundle.yaml

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1058]
Combine

```
- action: "copy"
  message: "Copying documentation and patching local links."
  source: "{input}/docs"
  target: "{output}/Documentation"
  replace:
    from: "\\(./(\\w+)\\.md\\)"
    to: "(./\\g<1>.html)"
  includes:
    - "ReleaseNotes.md"
    - "MajorVersionMigration.md"
- action: "copy"
  message: "Copying namespace document to Documentation directory and patching local links."
  source: "{input}/docs/Namespace.md"
  target: "{output}/Documentation/Namespace.md"
  replace:
    from: "\\(./(\\w+)\\.md\\)"
    to: "(./\\g<1>.html)"
```

into

```
- action: "copy"
  message: "Copying documentation and patching local links."
  source: "{input}/docs"
  target: "{output}/Documentation"
  replace:
    from: "\\(./(\\w+)\\.md\\)"
    to: "(./\\g<1>.html)"
  includes:
    - "ReleaseNotes.md"
    - "MajorVersionMigration.md"
    - "Namespace.md"
```

Not sure why it was divided into two in the first place. Probably someone didn't notice they were identical.
