### ISSUE TITLE
Create release notes template

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#338]
Something along the lines of:

```
Release X.x.x
=====
 
Major changes
-----
 
### Name
   - Description:
   - Issue(s):
   - Impact:
   - Migration plan:

Minor changes
-----
### Name
   - Description:
   - Issue(s):
   - Impact:
 
Patch changes
----- 
### Name
   - Description:
   - Issue(s):
```

Each PR should be accompanied by an entry in the release notes. If the developer has not made this entry, the PR should be rejected. Documentation should be updated to this effect.

**Comment by rjyounes** [comment]
Rebecca: Submit PR.

**Comment by rjyounes** [comment]
Added an additional line:

```
Release X.x.x
-----
 
### Major changes

#### Name
   - Description:
   - Motivation/Rationale:
   - Impact:
   - Migration plan:
   - Issue(s):

### Minor changes

#### Name
   - Description:
   - Motivation/Rationale:
   - Impact:
   - Issue(s):
 
### Patch changes

#### Name
   - Description:
   - Motivation/Rationale:
   - Issue(s):
```
